#!/bin/sh
# *************************************
# (C) 2020 IBM
# Fabian Salamanca <fsalamanca@ibm.com>
# *************************************

export PATH=${PATH}:/home/jenkins/apache-maven-3.6.3/bin

if [ -z ${JENKINS_HOME} ]; then
	JENKINS_HOME=/home/jenkins
fi

JAR="${JENKINS_HOME}/remoting.jar"

echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo
echo "JENKINS Service:port  |  HOME"
echo "${JENKINS_SERVICE_HOST}  : ${JENKINS_SERVICE_PORT}    |  ${JENKINS_HOME}"
echo
echo "JENKINS Tunnel - Jenkins URL"
echo "${JENKINS_TUNNEL}  |   ${JENKINS_URL}"
echo
echo "JENKINS Secret"
echo ${JENKINS_SECRET}

JENKINS_URL="http://${JENKINS_SERVICE_HOST}:${JENKINS_SERVICE_PORT}"
echo " curl: ${JENKINS_URL}/jnlpJars/remoting.jar -o ${JAR}"
curl -sS ${JENKINS_URL}/jnlpJars/remoting.jar -o ${JAR}
echo "Remoting downloaded"

java -version
#java -cp ${JAR} hudson.remoting.jnlp.Main -headless -url ${JENKINS_URL} ${JENKINS_SECRET}
ls ${JAR}
java -jar ${JAR} #hudson.remoting.jnlp.Main -headless -url ${JENKINS_URL} ${JENKINS_SECRET}

echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
